import sqlite3
import os
import logging
import datetime
from typing import Optional

logger = logging.getLogger(__name__)

class MutationCacheManager:
    """
    Manages a SQLite database for caching generated mutation descriptions.
    Ensures that if a report is re-run for the same variant, the Description is identical.
    """
    
    def __init__(self, db_path: str = "mutation_cache.db"):
        self.db_path = db_path
        self._init_db()

    def _init_db(self):
        """Initialize the database schema if it doesn't exist."""
        try:
            with sqlite3.connect(self.db_path) as conn:
                cursor = conn.cursor()
                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS variant_descriptions (
                        signature TEXT PRIMARY KEY,
                        description TEXT NOT NULL,
                        model_version TEXT,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                """)
                conn.commit()
        except Exception as e:
            logger.error(f"Failed to initialize mutation cache database: {e}")
            raise

    def get_description(self, signature: str) -> Optional[str]:
        """
        Retrieve a cached description by its signature.
        
        Args:
            signature: Unique string identifier for the mutation (e.g., "GENE:P.A123T")
            
        Returns:
            The cached description text, or None if not found.
        """
        try:
            with sqlite3.connect(self.db_path) as conn:
                cursor = conn.cursor()
                cursor.execute(
                    "SELECT description FROM variant_descriptions WHERE signature = ?", 
                    (signature,)
                )
                result = cursor.fetchone()
                if result:
                    return result[0]
        except Exception as e:
            logger.error(f"Error retrieving from mutation cache: {e}")
        
        return None

    def cache_description(self, signature: str, description: str, model_version: str = "unknown"):
        """
        Save a generated description to the cache.
        
        Args:
            signature: Unique string identifier for the mutation.
            description: The text generated by the LLM.
            model_version: Identifier for the model/prompt version used.
        """
        try:
            with sqlite3.connect(self.db_path) as conn:
                cursor = conn.cursor()
                cursor.execute(
                    """
                    INSERT OR REPLACE INTO variant_descriptions (signature, description, model_version, created_at)
                    VALUES (?, ?, ?, ?)
                    """,
                    (signature, description, model_version, datetime.datetime.now())
                )
                conn.commit()
                logger.info(f"Cached description for {signature}")
        except Exception as e:
            logger.error(f"Error caching description for {signature}: {e}")
    def get_all_signatures(self) -> list[str]:
        """Retrieve all signatures present in the cache."""
        try:
            with sqlite3.connect(self.db_path) as conn:
                cursor = conn.cursor()
                cursor.execute("SELECT signature FROM variant_descriptions")
                return [row[0] for row in cursor.fetchall()]
        except Exception as e:
            logger.error(f"Error listing cache signatures: {e}")
            return []
